name: PR Security Demo

on:
  pull_request_target

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Debug workspace
        run: |
          pwd
          ls -la

      - name: Make script executable
        run: chmod +x workflow.sh

      - name: Run script
        env:
          DEMO_SECRET: ${{ secrets.DEMO_SECRET }}
        run: bash workflow.sh
